### ISSUE TITLE
home page issues

### ISSUE THREAD

**Issue by lb2410** [lb2410/lorenebouboushian.org#2]
hey @edwardsharp so when i open the homepage and scroll down to look at upcoming events, unless i hold it there, the page auto-pops me back up to the photo scroll. halp!

would also be great to have the menu at the top right when you open the home page, and to have "upcoming engagements" bigger cause it's very tiny right now.

**Comment by edwardsharp** [comment]
oh yes! i'll fix that. 

menu at the top ...right? you mean the navigation menu that's currently below the photo carousel be at the top of the page?

**Comment by lb2410** [comment]
yeah that is the menu i mean, and yes at the top.
